spring.application.name=swapy_java

server.port=8082

# Configuracion de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/swapy
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect